spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: "******"
    password: "******"
    url: "jdbc:mysql://www.zhangzhuowei.com:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false"
  jpa:
    database-platform: "org.hibernate.dialect.MySQL5Dialect"
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: false
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
logging:
  level:
    root: INFO
    com.snow: INFO